[phases.setup]
nixPkgs = ["python3", "python3.pkgs.pip", "python3.pkgs.virtualenv"]

[phases.install]
cmds = [
    "python3 -m venv .venv",
    ". .venv/bin/activate",
    "pip install -r llm/requirements.txt"
]

[start]
cmd = ". .venv/bin/activate && FLASK_APP=llm/AI/LLM.py flask run --host=0.0.0.0 --port=${PORT:-5000}"