[phases.install]
cmds = ["python -m venv /llm/opt/venv", ". /llm/opt/venv/bin/activate", "pip install -r llm/requirements.txt"]

[start]
cmd = ". /llm/opt/venv/bin/activate && FLASK_APP=AI/LLM.py flask run --host=0.0.0.0 --port=${PORT:-5000}"