[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && FLASK_APP=AI/LLM.py flask run --host=0.0.0.0 --port=${PORT:-5000}"